In [1]:
import numpy as np
import jax
import torch
import torch_geometric

/home/tam/miniconda3/envs/egnn-3.11/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [20]:
flag = [True]
def remove_self_loop(data):
    if flag[0]: 
        print("transform")
        flag[0]=False
    edge_index = data.edge_index
    edge_attr = data.edge_attr
    new_edge_index, new_edge_attr = torch_geometric.utils.remove_self_loops(edge_index, edge_attr)
    data.edge_index = new_edge_index
    data.edge_attr = new_edge_attr
    return data

In [21]:
qm9_dataset = torch_geometric.datasets.QM9(root='data/QM9', pre_transform=remove_self_loop)

Processing...
  0%|          | 300/133885 [00:00<01:29, 1493.20it/s]

transform


100%|██████████| 133885/133885 [02:07<00:00, 1049.16it/s]
Done!


In [28]:
qm9_dataset

QM9(130831)

In [31]:
qm9_dataset.shuffle()

QM9(130831)

In [32]:
qm9_dataset[:10]

QM9(10)

In [29]:
qm9_dataset[10]

Data(x=[7, 11], edge_index=[2, 12], edge_attr=[12, 4], y=[1, 19], pos=[7, 3], z=[7], smiles='[H]C(=O)C([H])([H])[H]', name='gdb_11', idx=[1])

In [30]:
qm9_dataset.shuffle()[10]

Data(x=[20, 11], edge_index=[2, 42], edge_attr=[42, 4], y=[1, 19], pos=[20, 3], z=[20], smiles='[H]C([H])([H])C(=O)[C@]1([H])[N@H+]2[C@@]([H])(C([H])([H])[H])[C@@]2([H])C1([H])[H]', name='gdb_80584', idx=[1])

In [24]:
torch_geometric.utils.smiles.from_smiles('[H]C(=O)C([H])([H])[H]',with_hydrogen=True)

Data(x=[7, 9], edge_index=[2, 12], edge_attr=[12, 3], smiles='[H]C(=O)C([H])([H])[H]')

In [7]:
max([i.num_nodes for i in qm9_dataset])

29

In [10]:
import jax
import jax.numpy as jnp

In [13]:
loop_index = jnp.arange(0, 10).reshape((1, -1))
print(loop_index)
loop_index = jnp.repeat(loop_index, repeats=2, axis=0)
loop_index

[[0 1 2 3 4 5 6 7 8 9]]


Array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int32)

In [16]:
loop_index

Array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int32)

In [20]:
a = jnp.array([float("inf")])
a

Array([inf], dtype=float32)

In [21]:
a == float("inf")

Array([ True], dtype=bool)