In [1]:
import numpy as np
import jax
import torch
import torch_geometric

/home/tam/miniconda3/envs/egnn-3.11/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
qm9_dataset = torch_geometric.datasets.QM9(root='data/QM9')

Extracting data/QM9/raw/qm9.zip
Processing...
100%|██████████| 133885/133885 [01:54<00:00, 1171.02it/s]
Done!


In [7]:
qm9_dataset[10]

Data(x=[7, 11], edge_index=[2, 12], edge_attr=[12, 4], y=[1, 19], pos=[7, 3], z=[7], smiles='[H]C(=O)C([H])([H])[H]', name='gdb_11', idx=[1])

In [10]:
import jax
import jax.numpy as jnp

In [13]:
loop_index = jnp.arange(0, 10).reshape((1, -1))
print(loop_index)
loop_index = jnp.repeat(loop_index, repeats=2, axis=0)
loop_index

[[0 1 2 3 4 5 6 7 8 9]]


Array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int32)

In [16]:
loop_index

Array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int32)

In [20]:
a = jnp.array([float("inf")])
a

Array([inf], dtype=float32)

In [21]:
a == float("inf")

Array([ True], dtype=bool)